_security_logout:
    resource: security.route_loader.logout
    type: service

api_login:
    path: /api/login
    methods: ['POST']

api_token_refresh:
    path: /api/token/refresh
    methods: ['POST']
